const products = [
  {
    product_name: "Potatoes - Instant, Mashed",
    stock: 82,
    cost_by_unit: 1.25,
    description: "Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
    category: ["Rank"],
    warranty: 79,
    brand: "Oregon Ash",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997817/beautify/pexels-photo-3373725_umh7ug.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997817/beautify/pexels-photo-2533266_hiclv3.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997818/beautify/pexels-photo-1625037_kdpcof.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Cabbage - Nappa",
    stock: 52,
    cost_by_unit: 18.78,
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.",
    category: ["Rank"],
    warranty: 41,
    brand: "Cough",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997818/beautify/pexels-photo-1625037_kdpcof.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997817/beautify/pexels-photo-3373725_umh7ug.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997817/beautify/pexels-photo-2533266_hiclv3.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Muffins - Assorted",
    stock: 17,
    cost_by_unit: 27.28,
    description:
      "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.",
    category: ["Rank"],
    warranty: 20,
    brand: "Flurazepam",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997818/beautify/pexels-photo-1377034_jjy7le.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997818/beautify/pexels-photo-1625037_kdpcof.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997817/beautify/pexels-photo-3373725_umh7ug.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Fuji Apples",
    stock: 30,
    cost_by_unit: 28.04,
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    category: ["Rank"],
    warranty: 87,
    brand: "Theraplex",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-3373726_udus0b.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997818/beautify/pexels-photo-1377034_jjy7le.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997818/beautify/pexels-photo-1625037_kdpcof.jpg",
    ],
    discount: 3,
  },
  {
    product_name: "Turkey - Ground. Lean",
    stock: 68,
    cost_by_unit: 73.27,
    description:
      "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    category: ["Duobam"],
    warranty: 51,
    brand: "Aveeno",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-3685523_nmght1.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-3373726_udus0b.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997818/beautify/pexels-photo-1377034_jjy7le.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Wine - Red, Marechal Foch",
    stock: 38,
    cost_by_unit: 95.19,
    description:
      "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    category: ["Duobam"],
    warranty: 78,
    brand: "Strength",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-1619488_lydbjx.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-3685523_nmght1.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-3373726_udus0b.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Lid Tray - 12in Dome",
    stock: 64,
    cost_by_unit: 2.55,
    description:
      "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    category: ["Duobam"],
    warranty: 74,
    brand: "Oxytocin",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997822/beautify/pexels-photo-3373746_xauerl.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-1619488_lydbjx.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-3685523_nmght1.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Tendrils - Baby Pea, Organic",
    stock: 39,
    cost_by_unit: 30.01,
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    category: ["Zoolab"],
    warranty: 83,
    brand: "PhysiciansCare",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997822/beautify/pexels-photo-3321416_p02fhb.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997822/beautify/pexels-photo-3373746_xauerl.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997820/beautify/pexels-photo-1619488_lydbjx.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Rye Special Old",
    stock: 3,
    cost_by_unit: 44.59,
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    category: ["cuidado facial"],
    warranty: 7,
    brand: "Decafert",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997834/beautify/pexels-photo-4041392_yxv16a.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997822/beautify/pexels-photo-3321416_p02fhb.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997822/beautify/pexels-photo-3373746_xauerl.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Tea - Decaf 1 Cup",
    stock: 66,
    cost_by_unit: 15.93,
    description:
      "Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    category: ["cuidado facial"],
    warranty: 34,
    brand: "Glyburide",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997834/beautify/pexels-photo-4041391_h2anbn.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997834/beautify/pexels-photo-4041392_yxv16a.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997822/beautify/pexels-photo-3321416_p02fhb.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Sobe - Green Tea",
    stock: 15,
    cost_by_unit: 12.58,
    description:
      "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.",
    category: ["cuidado facial"],
    warranty: 49,
    brand: "Fumarate",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997835/beautify/pexels-photo-3851905_rnfoap.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997834/beautify/pexels-photo-4041391_h2anbn.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997834/beautify/pexels-photo-4041392_yxv16a.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Bread - Corn Muffaleta Onion",
    stock: 17,
    cost_by_unit: 17.46,
    description:
      "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    category: ["cuidado facial"],
    warranty: 18,
    brand: "Lotrel",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997835/beautify/pexels-photo-4612159_ssgijy.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997835/beautify/pexels-photo-3851905_rnfoap.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997834/beautify/pexels-photo-4041391_h2anbn.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Plasticforkblack",
    stock: 12,
    cost_by_unit: 41.24,
    description:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.",
    category: ["cuidado facial"],
    warranty: 14,
    brand: "Radiation",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-5938644_pvoegn.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-4735904_jpcfyp.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-4735904_jpcfyp.jpg",
    ],
    discount: 43,
  },
  {
    product_name: "Bread - Assorted Rolls",
    stock: 98,
    cost_by_unit: 42.85,
    description:
      "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    category: ["cuidado facial"],
    warranty: 43,
    brand: "Bluefish",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-4046316_fhtiow.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-5938644_pvoegn.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-4735904_jpcfyp.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Beer - Guiness",
    stock: 13,
    cost_by_unit: 8.25,
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.",
    category: ["cuidado facial"],
    warranty: 31,
    brand: "Prairie",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-6621322_q0xycw.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-4046316_fhtiow.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-5938644_pvoegn.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Bandage - Flexible Neon",
    stock: 22,
    cost_by_unit: 30.29,
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    category: ["cuidado facial"],
    warranty: 29,
    brand: "Ranitidine",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-6763379_ay6cq7.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-6621322_q0xycw.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997837/beautify/pexels-photo-4046316_fhtiow.jpg",
    ],
    discount: 8,
  },
  {
    product_name: "Lid Tray - 12in Dome",
    stock: 14,
    cost_by_unit: 3.12,
    description:
      "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    category: ["cuidado facial"],
    warranty: 30,
    brand: "METHADONE",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-4465124_wltrce.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-6763379_ay6cq7.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-6621322_q0xycw.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Lettuce - Frisee",
    stock: 54,
    cost_by_unit: 43.54,
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.",
    category: ["pestanas"],
    warranty: 100,
    brand: "SPF 36",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-4056460_uq59vd.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-4465124_wltrce.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-6763379_ay6cq7.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Soup - Cream Of Potato / Leek",
    stock: 49,
    cost_by_unit: 28.24,
    description:
      "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    category: ["pestanas"],
    warranty: 21,
    brand: "Amiodarone",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997840/beautify/pexels-photo-4046419_x9ideg.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-4056460_uq59vd.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-4465124_wltrce.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Oil - Grapeseed Oil",
    stock: 51,
    cost_by_unit: 79.53,
    description: "Donec posuere metus vitae ipsum.",
    category: ["pestanas"],
    warranty: 98,
    brand: "Hydrochloride",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997849/beautify/pexels-photo-7055832_lzg6cm.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997840/beautify/pexels-photo-4046419_x9ideg.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997839/beautify/pexels-photo-4056460_uq59vd.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Container - Foam Dixie 12 Oz",
    stock: 24,
    cost_by_unit: 81.0,
    description:
      "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    category: ["pestanas"],
    warranty: 18,
    brand: "Amiodarone",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997854/beautify/pexels-photo-7263026_oytwuw.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997849/beautify/pexels-photo-7055832_lzg6cm.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997840/beautify/pexels-photo-4046419_x9ideg.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Thyme - Lemon, Fresh",
    stock: 64,
    cost_by_unit: 49.34,
    description: "Duis bibendum.",
    category: ["pestanas"],
    warranty: 15,
    brand: "Hydrochloride",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997855/beautify/pexels-photo-7269475_e6clje.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997854/beautify/pexels-photo-7263026_oytwuw.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997849/beautify/pexels-photo-7055832_lzg6cm.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Tomatoes - Roma",
    stock: 14,
    cost_by_unit: 78.56,
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",
    category: ["pestanas"],
    warranty: 22,
    brand: "Amiodarone",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997857/beautify/pexels-photo-8140913_rxvoih.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997855/beautify/pexels-photo-7269475_e6clje.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997854/beautify/pexels-photo-7263026_oytwuw.jpg",
    ],
    discount: 39,
  },
  {
    product_name: "Veal - Inside Round / Top, Lean",
    stock: 87,
    cost_by_unit: 82.94,
    description:
      "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    category: ["pestanas"],
    warranty: 60,
    brand: "Escitalopram",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997866/beautify/pexels-photo-8478981_zycerm.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997857/beautify/pexels-photo-8140913_rxvoih.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997855/beautify/pexels-photo-7269475_e6clje.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Food Colouring - Blue",
    stock: 27,
    cost_by_unit: 39.8,
    description:
      "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
    category: ["pestanas"],
    warranty: 2,
    brand: "Dust",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997857/beautify/pexels-photo-7480272_j4hvax.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997866/beautify/pexels-photo-8478981_zycerm.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997857/beautify/pexels-photo-8140913_rxvoih.jpg",
    ],
    discount: 0,
  },
  {
    product_name: "Wine - Chablis J Moreau Et Fils",
    stock: 15,
    cost_by_unit: 1.63,
    description:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.",
    category: ["pestanas"],
    warranty: 48,
    brand: "Ziprasidon",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997866/beautify/pexels-photo-8478975_zmmnkv.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997857/beautify/pexels-photo-7480272_j4hvax.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997866/beautify/pexels-photo-8478981_zycerm.jpg",
    ],
    discount: 9,
  },
  {
    product_name: "Cheese - Goat",
    stock: 6,
    cost_by_unit: 77.43,
    description:
      "Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    category: ["pestanas"],
    warranty: 26,
    brand: "Doxepin",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-9518729_k5tuw7.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997866/beautify/pexels-photo-8478975_zmmnkv.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997857/beautify/pexels-photo-7480272_j4hvax.jpg",
    ],
    discount: 18,
  },
  {
    product_name: "Dc Hikiage Hira Huba",
    stock: 44,
    cost_by_unit: 45.06,
    description:
      "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    category: ["Flexidy"],
    warranty: 97,
    brand: "Norvasc",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-10514763_r1tfbu.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-9518729_k5tuw7.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997866/beautify/pexels-photo-8478975_zmmnkv.jpg",
    ],
    discount: 6,
  },
  {
    product_name: "Saskatoon Berries - Frozen",
    stock: 8,
    cost_by_unit: 47.21,
    description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    category: ["Flexidy"],
    warranty: 48,
    brand: "Deconge",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-8533265_jobm5g.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-10514763_r1tfbu.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-9518729_k5tuw7.jpg",
    ],
    discount: 9,
  },
  {
    product_name: "Cocoa Powder - Natural",
    stock: 87,
    cost_by_unit: 17.22,
    description:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    category: ["Flexidy"],
    warranty: 23,
    brand: "Neutrogena",
    image: [
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-8509192_r9xwdj.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-8533265_jobm5g.jpg",
      "https://res.cloudinary.com/estdia/image/upload/f_auto/v1645997867/beautify/pexels-photo-10514763_r1tfbu.jpg",
    ],
    discount: 0,
  },
];

module.exports = {
  products,
};
